name:                backend
version:             0.1.0.0
github:              "juanpaucar/yetanothertodo"
license:             MIT
author:              "Juan Paucar"
maintainer:          "me@juancarlos.io"
copyright:           "2019 Juan Paucar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/juanpaucar/yetanothertodo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
